#!/usr/bin/env python3
"""
Generate PROV / dcterms / schema.org / DCAT metadata in Turtle
for a matplotlib figure, using rdflib.

All semantic inputs (agent, activity, data, script) are passed as dictionaries.
"""

from datetime import datetime
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import rdflib
from ontolutils import urirefs, namespaces
from ontolutils.ex.dcat import Resource
from ontolutils.ex.prov import Activity, Agent, Person
from rdflib import Graph, Namespace, Literal
from rdflib.namespace import RDF, XSD


@namespaces(prov="http://www.w3.org/ns/prov#")
@urirefs(SoftwareAgent='prov:SoftwareAgent')
class SoftwareAgent(Agent):
    """Pydantic Model for http://www.w3.org/ns/prov#SoftwareAgent"""


# Namespaces
DCTERMS = Namespace("http://purl.org/dc/terms/")
PROV = Namespace("http://www.w3.org/ns/prov#")
SCHEMA = Namespace("https://schema.org/")
DCAT = Namespace("http://www.w3.org/ns/dcat#")


def _as_xsd_datetime(value):
    """
    Convert a datetime or ISO8601 string to an xsd:dateTime Literal.
    If value is None, returns None.
    """
    if value is None:
        return None
    if isinstance(value, datetime):
        # strip microseconds for cleanliness
        value = value.replace(microsecond=0).isoformat()
    return Literal(value, datatype=XSD.dateTime)


def figure_to_prov_graph(
        fig,
        figure_path,
        fig_uri: str,
        *,
        agent: Agent,
        activity: Activity,
        data_resources: list[Resource],
        script_agent: SoftwareAgent
):
    """
    Create an rdflib.Graph describing a figure generated by a given activity.

    Parameters
    ----------
    fig : matplotlib.figure.Figure
        The figure that was (or will be) saved.
    figure_path : str or Path
        Path to the image file (e.g. "figure1.png").
    agent : dict
        Dictionary describing the human prov:Agent, e.g.:
        {
            "id": "user1",
            "name": "Alice Example",
            "orcid": "0000-0002-1825-0097"   # optional
        }
    activity : dict
        Dictionary describing the prov:Activity, e.g.:
        {
            "id": "activity1",
            "label": "Generate sine plot",
            "startedAtTime": "2025-12-04T09:32:10Z",
            "endedAtTime":   "2025-12-04T09:32:11Z"
        }
        Times may be datetime objects or ISO8601 strings.
    data_resources : list[dict]
        Each dict describes a dcat:Resource used by the activity, e.g.:
        {
            "id": "dataset1",
            "title": "experiment_data.csv",
            "contentUrl": "data/experiment_data.csv",
            "encodingFormat": "text/csv"
        }
    script_agent : dict
        Dictionary describing the script as a prov:SoftwareAgent, e.g.:
        {
            "id": "script1",
            "name": "make_plot.py",
            "contentUrl": "code/make_plot.py",
            "encodingFormat": "text/x-python"
        }
    base_uri : str
        Base URI for all resources (used as namespace).

    Returns
    -------
    rdflib.Graph
        The populated RDF graph.
    """
    fig_uri = rdflib.URIRef(fig_uri)

    figure_path = Path(figure_path)
    g = Graph()
    g.bind("dcterms", DCTERMS)
    g.bind("prov", PROV)
    g.bind("schema", SCHEMA)
    g.bind("dcat", DCAT)
    g.bind("xsd", XSD)

    # -------- Figure info from matplotlib --------
    width_inches, height_inches = fig.get_size_inches()
    dpi = fig.dpi
    width_px = int(round(width_inches * dpi))
    height_px = int(round(height_inches * dpi))

    if getattr(fig, "_suptitle", None) is not None:
        fig_title = fig._suptitle.get_text()
    elif fig.axes:
        fig_title = fig.axes[0].get_title()
    else:
        fig_title = figure_path.stem

    # Use a derived ID for the figure (could also be passed as dict if you prefer)
    fig_id = f"{activity.id}-figure"

    # -------- Agent (human user) --------
    agent_uri = rdflib.URIRef(agent.id)
    agent_graph = Graph().parse(data=agent.model_dump_ttl(), format='turtle')

    for s, p, o in agent_graph:
        g.add((s, p, o))

    # -------- Script SoftwareAgent --------
    script_uri = rdflib.URIRef(script_agent.id)

    script_graph = Graph().parse(data=script_agent.model_dump_ttl(), format='turtle')
    for s, p, o in script_graph:
        g.add((s, p, o))

    # -------- Activity --------
    activity_uri = rdflib.URIRef(activity.id)
    activity_ttl = activity.serialize("ttl")
    activity_grpah = Graph().parse(data=activity_ttl, format='turtle')
    for s, p, o in activity_grpah:
        g.add((s, p, o))

    # Activity is associated with the human agent and the script software agent
    g.add((activity_uri, PROV.wasAssociatedWith, agent_uri))
    g.add((activity_uri, PROV.wasAssociatedWith, script_uri))

    # -------- Data resources (dcat:Resource, prov:used) --------
    for res in data_resources:

        resource_graph = Graph().parse(data=res.model_dump_ttl(), format='turtle')
        for s, p, o in resource_graph:
            g.add((s, p, o))

        res_uri = rdflib.URIRef(res.id)

        # Activity used this resource
        g.add((activity_uri, PROV.used, res_uri))

    # -------- Figure entity --------
    g.add((fig_uri, RDF.type, SCHEMA.ImageObject))
    g.add((fig_uri, RDF.type, PROV.Entity))

    g.add((fig_uri, DCTERMS.title, Literal(fig_title)))
    # If you want a created timestamp, you can reuse startedAtTime or add another value
    started = _as_xsd_datetime(activity.startedAtTime)
    if started is not None:
        g.add((fig_uri, DCTERMS.created, started))

    g.add((fig_uri, SCHEMA.encodingFormat,
           Literal(f"image/{figure_path.suffix.lstrip('.')}")))
    g.add((fig_uri, SCHEMA.contentUrl, Literal(figure_path.as_posix())))
    g.add((fig_uri, SCHEMA.width, Literal(width_px, datatype=XSD.integer)))
    g.add((fig_uri, SCHEMA.height, Literal(height_px, datatype=XSD.integer)))
    g.add((fig_uri, PROV.wasGeneratedBy, activity_uri))

    return g


def save_figure_with_prov(
        fig,
        figure_path,
        fig_uri,
        ttl_path=None,
        *,
        agent: Agent,
        activity: Activity,
        data_resources: list[dict],
        script_agent: dict
):
    """
    Save the figure and write a Turtle file describing it.
    """
    figure_path = Path(figure_path)
    fig.savefig(figure_path, bbox_inches="tight")

    if ttl_path is None:
        ttl_path = figure_path.with_suffix(".ttl")
    else:
        ttl_path = Path(ttl_path)

    g = figure_to_prov_graph(
        fig,
        figure_path,
        fig_uri=fig_uri,
        agent=agent,
        activity=activity,
        data_resources=data_resources,
        script_agent=script_agent
    )

    g.serialize(destination=str(ttl_path), format="turtle")
    return ttl_path


# -------------------------------------------------------------------
# Example usage
# -------------------------------------------------------------------
if __name__ == "__main__":
    # Make a simple plot
    x = np.linspace(0, 10, 100)
    y = np.sin(x)

    fig, ax = plt.subplots(figsize=(6, 4), dpi=150)
    ax.plot(x, y)
    ax.set_xlabel("x")
    ax.set_ylabel("sin(x)")
    fig.suptitle("Sine curve example")

    # Dictionaries for semantic inputs
    _agent = {
        "id": "https://orcid.org/0000-0002-1825-0097",
        "firstName": "Alice",
        "lastName": "Example",
        "identifier": "0000-0002-1825-0097",
    }
    agent = Person.model_validate(_agent)

    activity = Activity.model_validate({
        "id": "_:plotActivity1",
        "label": "Generate sine plot",
        "startedAtTime": "2025-12-04T09:32:10Z",
        "endedAtTime": "2025-12-04T09:32:11Z",
    })

    _data_resources = [
        {
            "id": "_:dataset1",
            "title": "sine_input.csv",
            "downloadUrl": "file://data/sine_input.csv",
            "encodingFormat": "text/csv",
        }
    ]
    data_resources = [Resource.model_validate(res) for res in _data_resources]

    _script_agent = {
        "id": "_:script1",
        "label": "make_plot.py",
        "type": "Python",
    }
    script_agent = SoftwareAgent.model_validate(_script_agent)

    ttl_file = save_figure_with_prov(
        fig,
        "figure1.png",
        fig_uri="http://example.org/figures/figure1",
        agent=agent,
        activity=activity,
        data_resources=data_resources,
        script_agent=script_agent,
    )

    print(f"Wrote Turtle metadata to: {ttl_file}")
